begin;
select plan(39);

select ok(exists(select 1 from supabase_migrations.schema_migrations where version='0011'),'ledger contains 0011');
select ok(exists(select 1 from supabase_migrations.schema_migrations where version='0012'),'ledger contains 0012');
select ok(to_regclass('public.stable_role_assignments') is not null,'stable role assignments exists');
select ok(to_regclass('public.horse_ownership_history') is not null,'ownership history exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='users' and column_name='primary_role_code'),'primary role column exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='horses' and column_name='deleted_at'),'horse soft delete exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='biochemistry_test_notes' and column_name='updated_at'),'comment updated timestamp exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='biochemistry_test_notes' and column_name='updated_by_user_id'),'comment updater exists');
select ok(exists(select 1 from pg_constraint where conname='biochemistry_test_notes_length_check'),'comment length constraint exists');
select ok(exists(select 1 from pg_constraint where conname='users_primary_role_code_check'),'primary role constraint exists');
select ok(to_regclass('public.idx_biochemistry_test_notes_active_test') is not null,'active comments index exists');
select ok(to_regclass('public.idx_stable_role_active_scope') is not null,'stable scope index exists');
select ok(to_regclass('public.idx_horse_ownership_history_horse_changed') is not null,'ownership audit index exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='stable_role_assignments'),'stable role RLS enabled');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='horse_ownership_history'),'ownership history RLS enabled');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('is_active_app_user','current_primary_role','has_active_stable_role','has_explicit_horse_role','can_comment_biochemistry_horse','can_manage_biochemistry_comment','is_trainer_for_horse','is_trainer_for_stable','can_manage_scoped_user','can_manage_horse_access_assignment','can_manage_stable_role_assignment')),11,'all role helpers exist');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('is_active_app_user','current_primary_role','has_active_stable_role','has_explicit_horse_role','can_comment_biochemistry_horse','can_manage_biochemistry_comment','is_trainer_for_horse','is_trainer_for_stable','can_manage_scoped_user','can_manage_horse_access_assignment','can_manage_stable_role_assignment') and p.prosecdef),11,'role helpers are security definer');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('is_active_app_user','current_primary_role','has_active_stable_role','has_explicit_horse_role','can_comment_biochemistry_horse','can_manage_biochemistry_comment','is_trainer_for_horse','is_trainer_for_stable','can_manage_scoped_user','can_manage_horse_access_assignment','can_manage_stable_role_assignment') and p.proconfig @> array['search_path=pg_catalog, public']),11,'role helpers have fixed search paths');
select is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('is_active_app_user','current_primary_role','has_active_stable_role','has_explicit_horse_role','can_comment_biochemistry_horse','can_manage_biochemistry_comment','is_trainer_for_horse','is_trainer_for_stable','can_manage_scoped_user','can_manage_horse_access_assignment','can_manage_stable_role_assignment') and has_function_privilege('anon',p.oid,'execute')),0,'anon cannot execute role helpers');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='stable_role_assignments'),4,'stable role policies exact');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='biochemistry_horse_access_assignments'),4,'horse role assignment policies exact');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='horses'),3,'horse policies exact');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='stables'),3,'stable policies exact');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='users' and cmd='UPDATE'),1,'user update policy exact');
select ok(not exists(select 1 from pg_policies where schemaname='public' and tablename='users' and policyname='users_update_self_or_admin'),'self status update policy absent');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='horse_ownership_history'),1,'ownership history is read-only to clients');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='biochemistry_test_notes'),3,'comment policies exact');
select is((select count(*)::integer from public.membership_levels where code in ('administrator','trainer','stable-manager','veterinarian','consultant','stable-hand','owner')),7,'definitive role seeds exist');
select is((select count(*)::integer from public.membership_level_permissions mlp join public.membership_levels ml on ml.id=mlp.membership_level_id join public.permissions p on p.id=mlp.permission_id where p.code='horse.comments.write' and ml.code in ('administrator','trainer','stable-manager','veterinarian','consultant','stable-hand')),6,'comment permission mappings exact');
select ok(exists(select 1 from public.membership_level_permissions mlp join public.membership_levels ml on ml.id=mlp.membership_level_id join public.permissions p on p.id=mlp.permission_id where ml.code='administrator' and p.code='platform.admin'),'administrator permission exists');
select is((select count(*)::integer from auth.users),0,'Auth baseline remains zero');
select is((select count(*)::integer from storage.buckets),0,'Storage bucket baseline remains zero');
select is((select count(*)::integer from storage.objects),0,'Storage object baseline remains zero');
select is((select count(*)::integer from public.biochemistry_lookup_values),1774,'lookup baseline unchanged');
select ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),'all public tables have RLS');
select ok(not exists(select 1 from pg_policies where schemaname='public' and tablename in ('horses','stables') and cmd='DELETE'),'horse and stable hard delete denied');
select ok(exists(select 1 from pg_constraint where conname='users_status_check' and convalidated),'user status constraint valid');
select ok(exists(select 1 from pg_constraint where conname='biochemistry_test_notes_length_check' and convalidated),'comment length constraint valid');
select ok(exists(select 1 from pg_trigger where tgname='horse_assignments_ownership_history' and not tgisinternal),'ownership audit trigger exists');

select * from finish();
rollback;
