import { SectionCard } from "@/components/layout/section-card";
import { getCommerceAdminSnapshot } from "@/lib/domain/commerce";

export default async function AdminCommercePage() {
  const snapshot = await getCommerceAdminSnapshot();
  const paidOrders = snapshot.orders.filter((order) => order.status === "paid").length;
  const paidPayments = snapshot.payments.filter((payment) => payment.status === "paid").length;
  const unsettledOrders = snapshot.orders.filter((order) => order.status !== "paid").length;
  const unsettledPayments = snapshot.payments.filter((payment) => payment.status !== "paid").length;
  const commerceMode = !snapshot.envReady
    ? "Setup required"
    : snapshot.orders.length > 0 || snapshot.payments.length > 0
      ? "Live activity"
      : "Ready for first transaction";

  return (
    <SectionCard
      eyebrow="Admin Commerce"
      title="Commerce activity"
      description="Review recent orders and payment events generated by the current checkout and webhook flows without leaving the admin workspace."
    >
      {!snapshot.envReady ? (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          Supabase service-role configuration is missing. Commerce administration will activate once the
          required environment variables are set.
        </div>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-5">
        <div className="rounded-[1.75rem] border border-ink/10 bg-sand p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">Orders</p>
          <p className="mt-4 font-display text-4xl text-ink">{snapshot.orders.length}</p>
          <p className="mt-3 text-sm leading-7 text-steel">Recent orders visible through the current commerce tables.</p>
        </div>
        <div className="rounded-[1.75rem] border border-ink/10 bg-sand p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">Paid orders</p>
          <p className="mt-4 font-display text-4xl text-ink">{paidOrders}</p>
          <p className="mt-3 text-sm leading-7 text-steel">Orders currently marked paid after checkout reconciliation.</p>
        </div>
        <div className="rounded-[1.75rem] border border-ink/10 bg-sand p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">Payments</p>
          <p className="mt-4 font-display text-4xl text-ink">{snapshot.payments.length}</p>
          <p className="mt-3 text-sm leading-7 text-steel">Recent payment records tracked by the webhook sync.</p>
        </div>
        <div className="rounded-[1.75rem] border border-ink/10 bg-sand p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">Paid payments</p>
          <p className="mt-4 font-display text-4xl text-ink">{paidPayments}</p>
          <p className="mt-3 text-sm leading-7 text-steel">Payments currently marked paid in the payment ledger.</p>
        </div>
        <div className="rounded-[1.75rem] border border-ink/10 bg-sand p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">Commerce mode</p>
          <p className="mt-4 text-sm font-semibold uppercase tracking-[0.14em] text-ink">{commerceMode}</p>
          <p className="mt-3 text-sm leading-7 text-steel">
            {!snapshot.envReady
              ? "The workspace is in setup mode until Supabase admin credentials are fully available."
              : "Use this view to monitor real orders, payments, and reconciliation progress."}
          </p>
        </div>
      </div>

      <div className="mt-8 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <div className="rounded-[2rem] border border-ink/10 bg-white p-6 shadow-panel">
          <p className="eyebrow">Orders</p>
          <h2 className="mt-3 font-display text-2xl text-ink">Recent order activity</h2>
          <div className="mt-6 grid gap-3">
            {snapshot.orders.length === 0 ? (
              <div className="rounded-2xl border border-ink/10 bg-sand px-4 py-4 text-sm text-steel">
                No commerce orders are available yet.
              </div>
            ) : (
              snapshot.orders.map((order) => (
                <div key={order.id} className="rounded-2xl border border-ink/10 bg-sand px-4 py-4">
                  <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
                    <p className="font-semibold text-ink">{order.itemSummary}</p>
                    <p className="text-sm font-semibold uppercase tracking-[0.14em] text-ember">{order.status}</p>
                  </div>
                  <p className="mt-2 text-sm text-steel">
                    {order.totalLabel} / {order.provider ?? "Unknown provider"}
                  </p>
                  <p className="mt-1 text-sm text-steel">
                    {order.userEmail ?? "No linked user"}{order.orderedAt ? ` / ${order.orderedAt}` : ""}
                  </p>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="grid gap-6">
          <div className="rounded-[2rem] border border-ink/10 bg-white p-6 shadow-panel">
            <p className="eyebrow">Payments</p>
            <h2 className="mt-3 font-display text-2xl text-ink">Recent payment activity</h2>
            <div className="mt-6 grid gap-3">
              {snapshot.payments.length === 0 ? (
                <div className="rounded-2xl border border-ink/10 bg-sand px-4 py-4 text-sm text-steel">
                  No payment records are available yet.
                </div>
              ) : (
                snapshot.payments.map((payment) => (
                  <div key={payment.id} className="rounded-2xl border border-ink/10 bg-sand px-4 py-4">
                    <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
                      <p className="font-semibold text-ink">{payment.amountLabel}</p>
                      <p className="text-sm font-semibold uppercase tracking-[0.14em] text-ember">{payment.status}</p>
                    </div>
                    <p className="mt-2 text-sm text-steel">
                      {payment.provider ?? "Unknown provider"} / {payment.providerPaymentId ?? "No provider payment id"}
                    </p>
                    <p className="mt-1 text-sm text-steel">
                      {payment.orderId ? `Order ${payment.orderId}` : "No linked order"}
                      {payment.paidAt ? ` / ${payment.paidAt}` : ""}
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="rounded-[2rem] border border-ink/10 bg-white p-6 shadow-panel">
            <p className="eyebrow">Reconciliation</p>
            <h2 className="mt-3 font-display text-2xl text-ink">What still needs attention</h2>
            <div className="mt-6 grid gap-3">
              <div className="rounded-2xl border border-ink/10 bg-sand px-4 py-4 text-sm text-ink">
                <p className="font-semibold">Orders still open</p>
                <p className="mt-1 text-steel">{unsettledOrders} orders are not yet marked paid.</p>
              </div>
              <div className="rounded-2xl border border-ink/10 bg-sand px-4 py-4 text-sm text-ink">
                <p className="font-semibold">Payments still open</p>
                <p className="mt-1 text-steel">{unsettledPayments} payments are not yet marked paid.</p>
              </div>
              <div className="rounded-2xl border border-ink/10 bg-sand px-4 py-4 text-sm text-ink">
                <p className="font-semibold">Operational note</p>
                <p className="mt-1 text-steel">
                  Use this view after checkout and webhook tests to confirm orders, payments, and user linkage are all landing in the expected tables.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </SectionCard>
  );
}
