-- Restrict application-owned SECURITY DEFINER helpers to authenticated callers.
alter function public.current_app_user_id() set search_path = pg_catalog, public;
alter function public.has_permission(text) set search_path = pg_catalog, public;
alter function public.is_admin() set search_path = pg_catalog, public;
alter function public.current_member_profile_id() set search_path = pg_catalog, public;
alter function public.can_access_horse(uuid) set search_path = pg_catalog, public;
alter function public.can_manage_horse_records(uuid) set search_path = pg_catalog, public;
alter function public.has_stable_scope(uuid) set search_path = pg_catalog, public;
alter function public.can_write_stable_scope(uuid) set search_path = pg_catalog, public;
alter function public.can_read_biochemistry_horse(uuid) set search_path = pg_catalog, public;
alter function public.can_write_biochemistry_horse(uuid) set search_path = pg_catalog, public;
alter function public.can_soft_delete_biochemistry_horse(uuid) set search_path = pg_catalog, public;
revoke execute on function public.current_app_user_id() from public, anon;
revoke execute on function public.has_permission(text) from public, anon;
revoke execute on function public.is_admin() from public, anon;
revoke execute on function public.current_member_profile_id() from public, anon;
revoke execute on function public.can_access_horse(uuid) from public, anon;
revoke execute on function public.can_manage_horse_records(uuid) from public, anon;
revoke execute on function public.has_stable_scope(uuid) from public, anon;
revoke execute on function public.can_write_stable_scope(uuid) from public, anon;
revoke execute on function public.can_read_biochemistry_horse(uuid) from public, anon;
revoke execute on function public.can_write_biochemistry_horse(uuid) from public, anon;
revoke execute on function public.can_soft_delete_biochemistry_horse(uuid) from public, anon;
grant execute on function public.current_app_user_id() to authenticated;
grant execute on function public.has_permission(text) to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.current_member_profile_id() to authenticated;
grant execute on function public.can_access_horse(uuid) to authenticated;
grant execute on function public.can_manage_horse_records(uuid) to authenticated;
grant execute on function public.has_stable_scope(uuid) to authenticated;
grant execute on function public.can_write_stable_scope(uuid) to authenticated;
grant execute on function public.can_read_biochemistry_horse(uuid) to authenticated;
grant execute on function public.can_write_biochemistry_horse(uuid) to authenticated;
grant execute on function public.can_soft_delete_biochemistry_horse(uuid) to authenticated;
